Update README.md
JustinReiter/wombat-symx pull request #30
Opened 2023-03-06 20:12 UTC by jliaz

* add a more descriptive/accurate description to described command

2023-03-06 20:13 UTC, AmanPal-Singh requested changes
Fix typo

2023-03-06 20:13 UTC, JustinReiter requested changes

2023-03-06 20:13 UTC, JustinReiter commented on README.md
> +To updat the project dependencies, use:
You misspelled `update`

2023-03-06 20:13 UTC, jliaz commented on README.md
> +To updat the project dependencies, use:
Oops! Thanks for the catch :)

2023-03-06 20:15 UTC, AmanPal-Singh approved these changes

2023-03-06 20:16 UTC, BenjaminBLi commented
squash your commits

2023-03-06 21:04 UTC, AmanPal-Singh commented
![image](https://user-images.githubusercontent.com/26210354/223230400-7eddbe63-f6ea-4d2a-bd78-0f4a0b1931f6.png)

2023-03-07 03:55 UTC, jliaz commented
> squash your commits

Please approve my changes when you have the bandwidth :)

2023-03-07 03:55 UTC, JustinReiter commented
Closing for inactivity

2023-03-07 03:55 UTC, closed without merging

2023-03-08 18:43 UTC, AmanPal-Singh commented
Can we reopen this PR? Issue is not resolved.